= YubiHSM

This repositoriy contains the source code of two crates. A low-level
FFI re-export of libyubihsm called `libyubihsm-sys`, and a more
ergonomic and idiomatic library called `yubihsmrs`.

== Building

To build the two libraries a normal Rust toolchain is required, stable
Rust will suffice.

Both libraries link against libyubihsm which must be installed on your
system. By default `libyubihsm-sys` will try to use `pkg-config` to
locate the native library and obtain the necessary information to use
it. A different path can be specified by setting the `YUBIHSM_LIB_DIR`
enviroment varible to point to a built version of libyubihsm.

It is also possible to build a local checkout of libyubihsm by
enabling the `buildlib` feature. This requires `cmake`.

=== Note about building

Currently neither crate has been published to crates.io. This means
that either a local or a git path should be specified when adding them
as dependencies.

== License

....
 Copyright 2015-2018 Yubico AB

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
....
