name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Install libyubihsm build dependencies
      run: sudo apt-get install libedit-dev libcurl4-openssl-dev libusb-1.0-0-dev gengetopt help2man libpcsclite-dev
    - name: Build
      run: cargo build --verbose --features buildlib
    - name: Run tests
      run: cargo test --verbose --features buildlib
